added list() method to FileSystem
oaplatform/oap pull request #291
Opened 2024-04-18 14:47 UTC by alebastrov

2024-04-18 16:48 UTC, nofateg requested changes

2024-04-18 16:48 UTC, nofateg commented on oap-storage/oap-storage-cloud/src/main/java/oap/storage/cloud/FileSystem.java
> +    public PageSet<? extends StorageMetadata> list( String path, String container, ListContainerOptions options ) {
You need to add a test for the new API

2024-04-18 16:48 UTC, nofateg commented on oap-storage/oap-storage-cloud/src/main/java/oap/storage/cloud/FileSystem.java
> +    public PageSet<? extends StorageMetadata> list( String path, String container, ListContainerOptions options ) {
You need to add another function with CloudURI parameter instead of String

2024-04-18 16:48 UTC, nofateg commented on oap-storage/oap-storage-cloud/src/main/java/oap/storage/cloud/FileSystem.java
> +    public PageSet<? extends StorageMetadata> list( String path, String container, ListContainerOptions options ) {
I suggest not exposing the jclouds API. For the cloud list options, it makes sense to create our class.

2024-04-19 07:08 UTC, alebastrov commented on oap-storage/oap-storage-cloud/src/main/java/oap/storage/cloud/FileSystem.java
> +    public PageSet<? extends StorageMetadata> list( String path, String container, ListContainerOptions options ) {
already added

2024-04-19 13:41 UTC, AlexDmitriychuk submitted a review, later dismissed

2024-04-23 09:05 UTC, nofateg approved these changes

2024-05-10 08:59 UTC, nofateg approved these changes

2024-05-10 09:03 UTC, merged